get_filename_component(_DEP_NAME ${CMAKE_CURRENT_LIST_DIR} NAME)
string(TOUPPER ${_DEP_NAME} _DEP_UNAME)

#set(_DEP_VER blade_cpp_sdk_gpu-3.18.0-Linux)
set(_DEP_VER blade_cpp_sdk_gpu-0.0.0-Linux)
set(_DEP_URL s3://mob-emr-test/ml-platform/ml-thirdparty-libs/${_DEP_VER}.tar.gz)
message(STATUS "${_DEP_UNAME} is ${_DEP_URL}")

set(_DEP_PREFIX ${${_DEP_UNAME}_PREFIX})
if("${_DEP_PREFIX}" STREQUAL "")
    if("${DEPS_DIR}" STREQUAL "")
        set(_DEP_PREFIX ${CMAKE_CURRENT_LIST_DIR})
    else()
        set(_DEP_PREFIX ${DEPS_DIR}/${_DEP_NAME})
    endif()
    set(${_DEP_UNAME}_PREFIX ${_DEP_PREFIX})
endif()
if("${DEPS_DIR}" STREQUAL "")
    get_filename_component(DEPS_DIR ${CMAKE_CURRENT_LIST_DIR} DGIRECTORY)
    message(STATUS "Dependencies directory has been set to: ${DEPS_DIR}")
endif()
message(STATUS "${_DEP_UNAME}_PREFIX: ${_DEP_PREFIX}")

CheckVersion()

if(NOT EXISTS ${_DEP_PREFIX}/lib/libtorch_addons_tensorrt_bridge.so)
    if(NOT EXISTS ${CMAKE_CURRENT_LIST_DIR}/packages/${_DEP_VER}.tar.gz)
        file(MAKE_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/packages)
        message(STATUS "Downloading ${_DEP_NAME}: ${_DEP_URL}")
        execute_process(
            COMMAND aws s3 cp ${_DEP_URL} ${CMAKE_CURRENT_LIST_DIR}/packages/
            RESULT_VARIABLE rc)
        if(NOT "${rc}" STREQUAL "0")
            message(FATAL_ERROR "Downloading ${_DEP_NAME}: ${_DEP_URL} - FAIL")
        endif()
        message(STATUS "Downloading ${_DEP_NAME}: ${_DEP_URL} - done")
    endif()
    set(TAR ON)
    if(${TAR})
        message(STATUS "Extracting ${_DEP_NAME}")
        execute_process(
            COMMAND tar -zxvf ${CMAKE_CURRENT_LIST_DIR}/packages/${_DEP_VER}.tar.gz --strip-components=3 -C ${DEPS_DIR}/${_DEP_NAME}
            RESULT_VARIABLE rc)
        if(NOT "${rc}" STREQUAL "0")
            message(FATAL_ERROR "Extracting ${_DEP_NAME} - FAIL")
        endif()
        message(STATUS "Extracting ${_DEP_NAME} - done")
    endif()
    file(REMOVE_RECURSE ${CMAKE_CURRENT_LIST_DIR}/packages)
endif()

if(EXISTS ${_DEP_PREFIX}/bin)
    set(_DEP_BIN_DIR ${_DEP_PREFIX}/bin)
    set(${_DEP_UNAME}_BIN_DIR ${_DEP_BIN_DIR})
endif()
if(EXISTS ${_DEP_PREFIX}/lib)
    set(_DEP_LIB_DIR ${_DEP_PREFIX}/lib)
    set(${_DEP_UNAME}_LIB_DIR ${_DEP_LIB_DIR})
endif()
if(EXISTS ${_DEP_PREFIX}/share)
    set(_DEP_LIB_DIR ${_DEP_PREFIX}/share)
    set(${_DEP_UNAME}_SHARE ${_DEP_LIB_DIR})
endif()
if(EXISTS ${_DEP_PREFIX}/include)
    set(_DEP_INCLUDE_DIR ${_DEP_PREFIX}/include)
    set(${_DEP_UNAME}_INCLUDE_DIR ${_DEP_INCLUDE_DIR})
endif()

list(FIND CMAKE_PREFIX_PATH ${_DEP_PREFIX} _DEP_INDEX)
if(_DEP_INDEX EQUAL -1)
    list(APPEND CMAKE_PREFIX_PATH ${_DEP_PREFIX})
endif()

if(NOT TARGET ${_DEP_NAME}::${_DEP_NAME} AND EXISTS ${_DEP_PREFIX}/lib/libtorch_addons.so)
    add_library(libtorch_addons SHARED IMPORTED)
    set_target_properties(libtorch_addons PROPERTIES IMPORTED_LOCATION "${_DEP_PREFIX}/lib/libtorch_addons.so")
    add_library(libtorch_addons_tensorrt_bridge SHARED IMPORTED)
    set_target_properties(libtorch_addons_tensorrt_bridge PROPERTIES IMPORTED_LOCATION "${_DEP_PREFIX}/lib/libtorch_addons_tensorrt_bridge.so")
    set(PAI_BLADE_LIBRARIES libtorch_addons libtorch_addons_tensorrt_bridge) 
    #set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE) 
    #set(CMAKE_INSTALL_RPATH "${_DEP_PREFIX}/lib")
    
    #add_library(${_DEP_NAME}::${_DEP_NAME} INTERFACE IMPORTED)
    #set_target_properties(${_DEP_NAME}::${_DEP_NAME} PROPERTIES 
         #IMPORTED_LOCATION "${_DEP_PREFIX}/lib"
         #INTERFACE_LINK_LIBRARIES  "${PAI_BLADE_LIBRARIES}"
         #INTERFACE_LINK_DIRECTORIES "${_DEP_PREFIX}/lib")
    #INTERFACE_LINK_LIBRARIES "${libpai_blade}"
    #INTERFACE_LINK_DIRECTORIES "${_DEP_PREFIX}/lib")
    #target_link_libraries(${_DEP_NAME}::${_DEP_NAME} PUBLIC ${PAI_BLADE_LIBRARIES})
    #target_link_directories(${_DEP_NAME}::${_DEP_NAME} PUBLIC ${_DEP_PREFIX}/lib)
    #add_custom_target(${_DEP_NAME}::${_DEP_NAME})
    #add_dependencies(${libpai_blade} ${_DEP_NAME}::${_DEP_NAME})
    #target_link_libraries(${_DEP_NAME}::${_DEP_NAME} INTERFACE libtorch_addons libtorch_addons_tensorrt_bridge)
endif()

unset(_DEP_NAME)
unset(_DEP_UNAME)
unset(_DEP_VER)
unset(_DEP_URL)
unset(_DEP_PREFIX)
unset(_DEP_BIN_DIR)
unset(_DEP_LIB_DIR)
unset(_DEP_INCLUDE_DIR)

