get_filename_component(_DEP_NAME ${CMAKE_CURRENT_LIST_DIR} NAME)
string(TOUPPER ${_DEP_NAME} _DEP_UNAME)
string(REPLACE "_" "-" _DEP_LNAME "${_DEP_NAME}")
set(_DEP_CUR_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${CMAKE_CURRENT_LIST_DIR}/../utils.cmake)
set(_DEP_VER 2.0.4)
set(_DEP_URL https://codeload.github.com/sparsehash/${_DEP_NAME}/tar.gz/refs/tags/${_DEP_NAME}-${_DEP_VER})
set(_DEP_PREFIX ${${_DEP_UNAME}_PREFIX})
if ("${_DEP_PREFIX}" STREQUAL "")
    if ("${DEPS_DIR}" STREQUAL "")
        set(_DEP_PREFIX ${CMAKE_CURRENT_LIST_DIR})
    else ()
        set(_DEP_PREFIX ${DEPS_DIR}/${_DEP_NAME})
    endif ()
    set(${_DEP_UNAME}_PREFIX ${_DEP_PREFIX})
endif ()
if ("${DEPS_DIR}" STREQUAL "")
    get_filename_component(DEPS_DIR ${CMAKE_CURRENT_LIST_DIR} DIRECTORY)
    message(STATUS "Dependencies directory has been set to: ${DEPS_DIR}")
endif ()
message(STATUS "${_DEP_UNAME}_PREFIX: ${_DEP_PREFIX}")

CheckVersion()

if (NOT EXISTS ${_DEP_PREFIX}/lib/pkgconfig/libsparsehash.pc)
    DownloadDep()
    ExtractDep()
    Configure()
    MakeBuild()
    MakeInstall()
    DoClean()
endif ()

SetDepPath()
AppendCMakePrefix()

if (NOT TARGET google::${_DEP_NAME})
    add_library(google::${_DEP_NAME} INTERFACE IMPORTED)
    set_target_properties(google::${_DEP_NAME} PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${_DEP_INCLUDE_DIR}")
endif ()

unset(_DEP_NAME)
unset(_DEP_UNAME)
unset(_DEP_LNAME)
unset(_DEP_VER)
unset(_DEP_URL)
unset(_DEP_PREFIX)
unset(_DEP_BIN_DIR)
unset(_DEP_LIB_DIR)
unset(_DEP_INCLUDE_DIR)
unset(_DEP_CUR_DIR)
