include(${CMAKE_CURRENT_LIST_DIR}/../check.cmake)
function(Process)
    if (NOT CMAKE_CXX_STANDARD)
        set(CMAKE_CXX_STANDARD 14)
    endif ()

    PrepareDep(20211102.0 MODULES absl_base)
    DownloadDep(AUTHOR abseil PROJECT abseil-cpp SPEED_UP_FILE abseil-cpp-${_DEP_VER}.tar.gz)
    Ninja(ARGS -DABSL_BUILD_TESTING=OFF -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
    PostProcess()
endfunction(Process)
Process()
#ProcessAddLibrary()
ProcessFindPackage(absl)